apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: default                       # Default ServiceAccount name
    namespace: {{ .Values.namespace }}  # Replace with the namespace of your webhook
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRole.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
