apiVersion: v1
kind: Pod
metadata:
  name: appropriate-curl
  namespace: mutatingwh
  labels:
    app: client
spec:
  containers:
  - name: appropriate-curl
    image: appropriate/curl
    command: ['sh', '-c', 'while true; do sleep 5; done']
    securityContext:
      readOnlyRootFilesystem: true  # ✅ Fixes AquaSec security warning
      allowPrivilegeEscalation: false  # ✅ Prevents privilege escalation
      runAsNonRoot: true  # ✅ Ensures the container does not run as root
      capabilities:
        drop:
          - ALL  # ✅ Removes unnecessary Linux capabilities
