---
apiVersion: v1
kind: Pod
metadata:
  name: live-true
  namespace: cloudtest
  labels:
    env: uat
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        readOnlyRootFilesystem: true  # ✅ Fixes AquaSec security warning
        allowPrivilegeEscalation: false  # ✅ Prevents privilege escalation
        runAsNonRoot: true  # ✅ Ensures the container does not run as root
        capabilities:
          drop:
            - ALL  # ✅ Removes unnecessary Linux capabilities
