apiVersion: v1
kind: Pod
metadata:
  annotations:
    ad.datadoghq.com/tags: '{"env": "prd", "cluster_type": "blue", "namespace": "mutatingwh2",
      "client_name": "mutatingwh1", "client_environment": "default", "release": "N/A. No
      release name found", "live": "false", "service": "tecsys-elite-appnode", "role":
      "app", "kind": "Stateful", "region": "us-east-1"}'
  labels:
    run: nginx
  name: live-false
  namespace: mutatingwh2
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      readOnlyRootFilesystem: true  # ✅ Fixes AquaSec security warning
      allowPrivilegeEscalation: false  # ✅ Prevents privilege escalation
      runAsNonRoot: true  # ✅ Ensures the container does not run as root
      capabilities:
        drop:
          - ALL  # ✅ Removes unnecessary Linux capabilities
  restartPolicy: Always
