---
apiVersion: v1
kind: Pod
metadata:
  name: no-annotations
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: nginx
      imagePullPolicy: Always
      securityContext:
        readOnlyRootFilesystem: true  # ✅ Fixes AquaSec security warning
        allowPrivilegeEscalation: false  # ✅ Prevents privilege escalation
        runAsNonRoot: true  # ✅ Ensures the container does not run as root
        capabilities:
          drop:
            - ALL  # ✅ Removes unnecessary Linux capabilities
